version: "3.7"

services:
    
    router:
        image: bayrell/cloud_router:0.1.0
        hostname: "{{.Service.Name}}.{{.Task.ID}}.local"
        volumes:
            - "router_data:/data"
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
        env_file:
            - env.cloud_os.conf
        environment:
            DNS_RESOLVER: 127.0.0.11
            CLOUD_SOFTWARE_NAME: "bayrell.cloud_os.router"
        deploy:
            replicas: 1
            endpoint_mode: dnsrr
            update_config:
                parallelism: 1
                failure_action: rollback
                delay: 5s
            restart_policy:
                condition: "on-failure"
                delay: 10s
                window: 120s
            placement:
                constraints:
                    - node.type.name == docker0
        networks:
            - cloud_router
        ports:
          - target: 80
            published: 80
            protocol: tcp
            mode: host
        logging:
            driver: journald

volumes:
    router_data:

networks:
    
    cloud_router:
        external: true
