version: "3.7"

services:

    mysql1:
        image: bayrell/alpine_mariadb:10.4
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql-mode="" --ft_min_word_len=1 --wait_timeout=600 --max_allowed_packet=1G
        hostname: "{{.Service.Name}}.{{.Task.ID}}.local"
        volumes:
            - "mysql1_data:/data"
        env_file:
            - ../keys/env.cloud_os.conf
        deploy:
            replicas: 1
            endpoint_mode: dnsrr
            update_config:
                parallelism: 1
                failure_action: rollback
                delay: 5s
            restart_policy:
                condition: "on-failure"
                delay: 10s
                window: 120s
            placement:
                constraints:
                    - node.labels.name == docker0
        networks:
            - backend
        logging:
            driver: journald

volumes:
    mysql1_data:

networks:

    backend:
        driver: overlay
        attachable: true
