version: "3.7"

secrets:
    AUTH_PUBLIC_KEY:
        file: ../keys/auth_public.key


services:
    
    time_planner:
        image: bayrell/time_planner:0.1.0
        hostname: "{{.Service.Name}}.{{.Task.ID}}.local"
        volumes:
            - "time_planner_data:/data"
        secrets:
            - AUTH_PUBLIC_KEY
        env_file:
            - ../keys/env.prod.conf
        environment:
            CLOUD_SOFTWARE_NAME: "bayrell.time_planner"
        deploy:
            replicas: 1
            endpoint_mode: dnsrr
            update_config:
                parallelism: 1
                failure_action: rollback
                delay: 5s
            restart_policy:
                condition: "on-failure"
                delay: 10s
                window: 120s
            placement:
                constraints:
                    - node.labels.name == docker0
        networks:
            - backend
            - cloud_router
        logging:
            driver: journald


    time_planner_cron:
        image: bayrell/time_planner:0.1.0
        hostname: "{{.Service.Name}}.{{.Task.ID}}.local"
        volumes:
            - "time_planner_data:/data"
        secrets:
            - AUTH_PUBLIC_KEY
        env_file:
            - env.prod.conf
        environment:
            CLOUD_SOFTWARE_NAME: "bayrell.time_planner"
            ENABLE_CRON: 1
        deploy:
            replicas: 1
            endpoint_mode: dnsrr
            update_config:
                parallelism: 1
                failure_action: rollback
                delay: 5s
            restart_policy:
                condition: "on-failure"
                delay: 10s
                window: 120s
            placement:
                constraints:
                    - node.labels.name == docker0
        networks:
            - backend
            - cloud_router
        logging:
            driver: journald
            
volumes:
    time_planner_data:

networks:
    
    cloud_router:
        external: true
    
    backend:
        driver: overlay
        attachable: true
